apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sonarqube  # Optional: if not already in metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          securityContext:                  # ✅ Added block
            allowPrivilegeEscalation: false
          env:
            - name: POSTGRES_USER
              value: "sonar"
            - name: POSTGRES_PASSWORD
              value: "sonarpass"
            - name: POSTGRES_DB
              value: "sonarqube"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
