apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube  # ✅ Added namespace to avoid default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
